---
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Enable Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Install Docker Compose plugin
  apt:
    name: docker-compose-plugin
    state: present
