---
- name: Configure EC2 instance
  hosts: voting-system
  become: yes
  gather_facts: yes

  tasks:
    - name: Wait for SSH to be ready
      wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        timeout: 30

  roles:
    - common
    - docker
    - nginx
