---
- name: Deploy Smart Voting System with Face Recognition
  hosts: voting-system
  become: yes
  gather_facts: yes

  vars:
    repo_url: "https://github.com/naveensaini9521/smart_voting_system_with_face_recognition.git"
    app_dir: "/var/www/smart_voting"
    app_user: "ubuntu"
    gunicor