---
- name: Infrastructure with Terraform
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    tf_dir: "../terraform"
    plan_file: "tfplan.out"
    key_path: "/home/naveen-saini/Desktop/AWS/devops-key.pem"

  tasks:
    - name: Run terraform fmt
      command: "terraform fmt -check"
      args:
        chdir: "{{ tf_dir }}"
      register: fmt_check
      failed_when: fmt_check.rc != 0
      changed_when: false

    - name: Run terraform validate
      command: "terraform validate"
      args:
        chdir: "{{ tf_dir }}"
      register: validate_out
      changed_when: false

    - name: Run terraform init
      command: "terraform init"
      args:
        chdir: "{{ tf_dir }}"
      register: tf_init
      changed_when: "'initialized' in tf_init.stdout"

    - name: Run terraform plan and save to file
      command: "terraform plan -out={{ plan_file }}"
      args:
        chdir: "{{ tf_dir }}"
      register: tf_plan
      changed_when: "'Plan:' in tf_plan.stdout"

    - name: Apply the saved plan
      command: "terraform apply -auto-approve {{ plan_file }}"
      args:
        chdir: "{{ tf_dir }}"
      register: tf_apply
      changed_when: "'apply' in tf_apply.stdout"

    - name: Get the public IP from Terraform output
      command: "terraform output -raw public_ip"
      args:
        chdir: "{{ tf_dir }}"
      register: tf_output
      changed_when: false

    - name: Set fact for public IP
      set_fact:
        instance_ip: "{{ tf_output.stdout }}"

    - name: Display instance IP
      debug:
        msg: "Provisioned instance IP is {{ instance_ip }}"

    - name: Add the new instance to the in-memory inventory
      add_host:
        name: "{{ instance_ip }}"
        groups: voting-system
        ansible_user: ubuntu
        ansible_ssh_private_key_file: "{{ key_path }}"
        ansible_python_interpreter: /usr/bin/python3

- name: Wait for SSH to be ready
  hosts: voting-system
  gather_facts: no
  tasks:
    - name: Wait for port 22
      wait_for:
        port: 22
        host: "{{ instance_ip }}"
        timeout: 60

- name: Configure the newly created instance
  hosts: voting-system
  become: yes
  gather_facts: yes

  roles:
    - common
    - docker
    - nginx
